POST http://localhost:3000/auth/refresh-token
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTc0NDE5NzE4NSwiZXhwIjoxNzQ0MTk3MTg4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.pITedqsl7dl3SGCqXNPFvR-yRcjOv_8n6LDdSq26uqs

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImlhdCI6MTc0NDE5NzIxMywiZXhwIjoxNzQ0MTk3Mjk5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.DYLptRiJ_fmV9HKd5ym-pybFWS3xYH_zHE3FJiqYhUA"
}